[workspace]
members = [
  "lib",

  "bin/shepherd",
  "bin/dummy-shepherd",
  "bin/tagged-shepherd",
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
strip = "symbols"
panic = "abort"
lto = "thin"
