[package]
name = "dummy-shepherd"
description = "dummy shepherd for testing the flock simulation library"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://github.com/superwhiskers/shepherd"
readme = "../readme.md"
edition = "2021"
license = "0BSD"

[dependencies]
serde_json = "1"
rand = "0.8"
anyhow = "1"

[dependencies.shepherd-lib]
path = "../../lib"
version = "*"
