[package]
name = "shepherd"
description = "flock simulation library frontend"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://github.com/superwhiskers/shepherd"
readme = "../../readme.md"
edition = "2021"
license = "0BSD"

[dependencies]
lexopt = "0.3"
tracing = "0.1"
anyhow = "1"
rand = "0.8"
petgraph = "0.7"

[dependencies.duckdb]
version = "1"
features = ["bundled"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["tracing-log"]

[dependencies.shepherd-lib]
path = "../../lib"
version = "*"
